using System;
using System.Collections.Generic;

namespace BOMApp
{
    public class OutputBuilder
    {
        private static readonly string Title = "Bill of Materials";
        private static readonly string LineBreak = "----------------------------------------------------------------";

        /// <summary>
        /// Builds a string that can be fed into the Widget Builder
        /// </summary>
        /// <param name="boms">List of strings generated by the Widget processors</param>
        /// <returns></returns>
        public static string BuildOutput(List<string> boms)
        {
            try
            {
                string returnedOutput;
                
                // Check that the list actually has some values in it
                if (boms.Count > 0)
                {
                    // Set up the standard headers
                    returnedOutput = $"{LineBreak}\r\n{Title}\r\n{LineBreak}";

                    // Loop through the list of BOMs to add them to the order
                    foreach (string bom in boms)
                    {
                        returnedOutput += $"\r\n{bom}";
                    }

                    // Add on the footer
                    returnedOutput += $"\r\n{LineBreak}";

                    return returnedOutput;
                }
                // If the list of BOMs is empty, we shouldn't have got here so throw an exception to abort
                else
                {
                    throw new Exception();
                }
            }
            // Catch in case anything unhandled does go wrong which will cause the process to abort
            catch
            {
                throw new Exception();
            }
        }
    }
}
